var movieList =  [
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },{
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },
    {
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },{
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    },{
        "name":"xyz",
        "rating":"2",
        "rdate":"22/12/22",
    }





];


module.exports = movieList;